// <auto-generated />
using System;
using GoodReviewBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodReviewBackend.Migrations
{
    [DbContext(typeof(GoodReviewDatabaseContext))]
    [Migration("20241216183913_PendingChangesMigration")]
    partial class PendingChangesMigration
    {
        /// <inheritdoc />
    }
}
